name: LAMDA-SSL
channels:
  - pyg
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - default
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/

dependencies:
  - matplotlib=3.5.0
  - numpy=1.19.2
  - pandas=1.3.4
  - pillow=8.4.0
  - pip=21.2.4
  - pyg=2.0.3
  - python=3.7.9
  - pytorch=1.10.1
  - scikit-learn=1.0.2
  - scipy=1.5.2
  - torchtext=0.11.1
  - torchvision=0.11.2
